### ISSUE TITLE
大佬，我贡献一个群晖的docker一键部署

### ISSUE THREAD

**Issue by docker-master** [GreenDamTan/DockerFile#3]
```yaml
version: "3.8" 
services:
  virtual-dsm:
    image: vdsm/virtual-dsm
    container_name: docker-virtual-dsm
    devices:
      - /dev/kvm # 挂载KVM设备，用于硬件虚拟化
      - /dev/dri # 挂载DRI设备，用于图形处理
    cap_add:
      - NET_ADMIN # 允许容器进行网络管理操作
    volumes:
      - /mnt/pve/ext4/lxc/docker/Dsm:/storage
    ports:
      - 5000:5000
    environment:
      - DISK_SIZE=20G # 虚拟DSM的磁盘大小为20G
      - RAM_SIZE=2G # 分配2G内存
      - CPU_CORES=1 # 分配1个CPU核心
      - GPU=Y # 启用GPU支持
      - TZ=Asia/Shanghai # 设置时区为亚洲/上海
      - URL=https://global.synologydownload.com/download/DSM/release/7.2.1/69057-1/DSM_VirtualDSM_69057.pat # DSM安装包下载URL
    restart: on-failure # 当容器运行失败时重启
    network_mode: bridge
```
